### PR TITLE
feat: add calyptus curriculum to tutrials in homepage

### PR DESCRIPTION
**Pull request by jim4067**
add the Calyptus Solana curriculum, `https://calyptus.co/learn-solana/` to tutorials.

### CODE REVIEW

**Review by acheroncrypto — COMMENTED** [review]
I'm not sure about this because the link takes you to a login page:

image

**Comment by jim4067** [comment]
@acheroncrypto, can we keep this till end of Feb when we separate our platform and open up the learning platform?

**Comment by acheroncrypto** [comment]
We can add external Solana tutorials but I think the link should at least point to something visible first, not a login screen without a sign up button.

**Comment by jim4067** [comment]
sounds good. let me get to this ASAP

**Pull request closed without merging**
